trigger:
- main

pool: local
variables:
  GIT_USERNAME: Balraj0017
  GIT_TOKEN: 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
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'mig/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    server-id: github
    server-username: $(GIT_USERNAME)
    server-password: $(GIT_TOKEN)
  displayName: Set up maven
  
- script: mvn clean package -DattachMuleSources -Pgithub deploy 
  displayName: Maven build deploy


        
